# Generated by Django 6.1 on 2026-08-15 12:44

import apps.accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('access_level', models.CharField(choices=[('COUNCIL_ADMIN', 'Council Admin'), ('CONSULTANT', 'Consultant'), ('AGENT', 'Agent'), ('GLOBAL_VIEW', 'Global View')], max_length=16)),
            ],
            options={
                'db_table': 'app_role',
            },
        ),
        migrations.CreateModel(
            name='SubConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant_name', models.CharField(max_length=160)),
                ('contract_ref', models.CharField(max_length=64)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Percent, e.g. 30.00', max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXITED', 'Exited')], default='PENDING', max_length=16)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
            ],
            options={
                'db_table': 'sub_consultant',
                'ordering': ['consultant_name'],
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenancy.council')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.approle')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.subconsultant')),
            ],
            options={
                'db_table': 'app_user',
            },
            managers=[
                ('objects', apps.accounts.managers.AppUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CouncilGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oversight_grants', to='tenancy.council')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'council_grant',
                'constraints': [models.UniqueConstraint(fields=('user', 'council'), name='uniq_council_grant')],
            },
        ),
        migrations.CreateModel(
            name='FieldAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_code', models.CharField(max_length=32)),
                ('device_imei', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXITED', 'Exited')], default='ACTIVE', max_length=16)),
                ('assigned_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='tenancy.wardzone')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'field_agent',
                'constraints': [models.UniqueConstraint(fields=('council', 'agent_code'), name='uniq_agent_code_per_council')],
            },
        ),
        migrations.AddConstraint(
            model_name='subconsultant',
            constraint=models.UniqueConstraint(fields=('council', 'contract_ref'), name='uniq_contract_ref_per_council'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "sub_consultant" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "sub_consultant" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "sub_consultant_tenant_isolation" ON "sub_consultant"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "sub_consultant_tenant_isolation" ON "sub_consultant";',
                'ALTER TABLE "sub_consultant" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "sub_consultant" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "field_agent" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "field_agent" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "field_agent_tenant_isolation" ON "field_agent"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "field_agent_tenant_isolation" ON "field_agent";',
                'ALTER TABLE "field_agent" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "field_agent" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
