# Generated by Django 6.1 on 2026-09-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("registry", "0003_payer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="subconsultant",
            name="contract_end_date",
            field=models.DateField(
                blank=True, help_text="Blank for an open-ended contract.", null=True
            ),
        ),
        migrations.AddField(
            model_name="subconsultant",
            name="contract_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subconsultant",
            name="registration_payer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultant",
                to="registry.payer",
            ),
        ),
        migrations.AlterField(
            model_name="approle",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("COUNCIL_ADMIN", "Council Admin"),
                    ("CONSULTANT", "Consultant"),
                    ("AGENT", "Agent"),
                    ("GLOBAL_VIEW", "Global View"),
                    ("REVENUE_OFFICER", "Revenue Officer"),
                ],
                max_length=16,
            ),
        ),
    ]
