# Generated by Django 6.1 on 2026-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_subconsultant_contract_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldagent",
            name="id_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="fieldagent",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NIN", "NIN"),
                    ("PASSPORT", "International Passport"),
                    ("DRIVERS_LICENSE", "Driver's License"),
                    ("VOTERS_CARD", "Voter's Card"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="fieldagent",
            name="next_of_kin_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="fieldagent",
            name="next_of_kin_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="subconsultant",
            name="authorized_signatory_id_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="subconsultant",
            name="authorized_signatory_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NIN", "NIN"),
                    ("PASSPORT", "International Passport"),
                    ("DRIVERS_LICENSE", "Driver's License"),
                    ("VOTERS_CARD", "Voter's Card"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="subconsultant",
            name="authorized_signatory_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="subconsultant",
            name="registered_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
