# Generated by Django 6.1 on 2026-09-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_appuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
