# Generated by Django 6.1 on 2026-09-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_appuser_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="councilgrant",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approle",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("COUNCIL_ADMIN", "Council Admin"),
                    ("CONSULTANT", "Consultant"),
                    ("AGENT", "Agent"),
                    ("GLOBAL_VIEW", "Global View"),
                    ("REVENUE_OFFICER", "Revenue Officer"),
                    ("SUPER_ADMIN", "Super Admin"),
                    ("PLATFORM_ADMIN", "Platform Admin"),
                    ("DEVOPS_ADMIN", "DevOps Admin"),
                    ("BD_VIEW", "BD / Account Manager"),
                    ("COMPLIANCE_VIEW", "Compliance View"),
                    ("FINANCE_ADMIN", "Finance Admin (ACDSL)"),
                    ("SUPPORT_ADMIN", "Support Admin"),
                    ("ANALYTICS_VIEW", "Analytics View"),
                    ("EXTERNAL_AUDITOR", "External Auditor"),
                    ("COUNCIL_IGR_HEAD", "Council IGR Head"),
                    ("COUNCIL_TREASURY", "Council Treasury"),
                    ("COUNCIL_AUDITOR", "Council Auditor"),
                    ("COUNCIL_IT", "Council IT"),
                    ("CONSULTANT_STAFF", "Consultant Staff"),
                    ("AGENT_SUPERVISOR", "Agent Supervisor"),
                    ("RATEPAYER", "Ratepayer"),
                    ("RATEPAYER_PROXY", "Ratepayer Proxy"),
                ],
                max_length=16,
            ),
        ),
    ]
