# Generated by Django 6.1 on 2026-09-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_councilgrant_expires_at_alter_approle_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
