# Generated by Django 6.1 on 2026-08-20 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=64)),
                ('record_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('PAYER', 'Payer')], max_length=16)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('CONFLICT', 'Conflict'), ('REJECTED', 'Rejected')], max_length=16)),
                ('result_ref', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_records', to='accounts.fieldagent')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
            ],
            options={
                'db_table': 'mobile_sync_record',
                'constraints': [models.UniqueConstraint(fields=('council', 'client_id'), name='uniq_council_client_id')],
            },
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "mobile_sync_record" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "mobile_sync_record" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "mobile_sync_record_tenant_isolation" ON "mobile_sync_record"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "mobile_sync_record_tenant_isolation" ON "mobile_sync_record";',
                'ALTER TABLE "mobile_sync_record" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "mobile_sync_record" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
