# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('revenue', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('BILLED', 'Billed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='registry.enumeratedasset')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('council_revenue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='revenue.councilrevenueitem')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='registry.payer')),
                ('rate_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='revenue.rateschedule')),
            ],
            options={
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_ref', models.CharField(blank=True, max_length=64, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PART_PAID', 'Part Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('SUPERSEDED', 'Superseded')], default='ISSUED', max_length=16)),
                ('due_date', models.DateField()),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_issued', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='registry.payer')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='billing.bill')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_lines', to='billing.assessment')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.bill')),
            ],
            options={
                'db_table': 'bill_line',
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['council', 'status'], name='bill_council_56a454_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['council', 'payer'], name='bill_council_83141e_idx'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "assessment" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "assessment" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "assessment_tenant_isolation" ON "assessment"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "assessment_tenant_isolation" ON "assessment";',
                'ALTER TABLE "assessment" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "assessment" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "bill" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "bill" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "bill_tenant_isolation" ON "bill"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "bill_tenant_isolation" ON "bill";',
                'ALTER TABLE "bill" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "bill" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
