# Generated by Django 6.1 on 2026-08-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('revenue', '0002_rateband_ratetier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='rate_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='revenue.rateband'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='rate_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='revenue.ratetier'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='rate_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='revenue.rateschedule'),
        ),
    ]
