# Generated by Django 6.1 on 2026-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_assessment_rate_band_assessment_rate_tier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billline",
            options={"ordering": ["position", "id"]},
        ),
        migrations.AddField(
            model_name="billline",
            name="arrears_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="billline",
            name="current_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="billline",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
