# Generated by Django 6.1 on 2026-09-23 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_backfill_billline_position_and_current_amount'),
        ('registry', '0010_payer_line_of_business'),
        ('tenancy', '0005_department_is_active_wardzone_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['council', 'created_at'], name='bill_council_3a788e_idx'),
        ),
    ]
