# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council_code', models.CharField(max_length=16, unique=True)),
                ('council_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'council',
                'ordering': ['council_code'],
            },
        ),
        migrations.CreateModel(
            name='CouncilConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_ref_prefix', models.CharField(help_text="e.g. KAC — used as bill_ref's leading segment", max_length=16, unique=True)),
                ('bill_due_days', models.PositiveSmallIntegerField(default=30)),
                ('revenue_bank_name', models.CharField(blank=True, max_length=120)),
                ('revenue_bank_account_number', models.CharField(blank=True, max_length=32)),
                ('revenue_bank_account_name', models.CharField(blank=True, max_length=160)),
                ('treasurer_name', models.CharField(blank=True, max_length=120)),
                ('treasurer_phone', models.CharField(blank=True, max_length=32)),
                ('print_signatory_name', models.CharField(blank=True, max_length=120)),
                ('print_signatory_title', models.CharField(blank=True, max_length=120)),
                ('council', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenancy.council')),
            ],
            options={
                'db_table': 'council_config',
            },
        ),
        migrations.CreateModel(
            name='WardZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward_code', models.CharField(max_length=32)),
                ('ward_name', models.CharField(max_length=120)),
                ('zone_type', models.CharField(choices=[('WARD', 'Ward'), ('ZONE', 'Zone'), ('DISTRICT', 'District')], default='WARD', max_length=16)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
            ],
            options={
                'db_table': 'ward_zone',
                'ordering': ['ward_name'],
                'constraints': [models.UniqueConstraint(fields=('council', 'ward_code'), name='uniq_ward_code_per_council')],
            },
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "council_config" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "council_config" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "council_config_tenant_isolation" ON "council_config"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "council_config_tenant_isolation" ON "council_config";',
                'ALTER TABLE "council_config" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "council_config" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "ward_zone" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "ward_zone" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "ward_zone_tenant_isolation" ON "ward_zone"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "ward_zone_tenant_isolation" ON "ward_zone";',
                'ALTER TABLE "ward_zone" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "ward_zone" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
