# Generated by Django 6.1 on 2026-09-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("department_name", models.CharField(max_length=160)),
                ("department_code", models.CharField(blank=True, max_length=32)),
                ("head_name", models.CharField(blank=True, max_length=160)),
                ("head_phone", models.CharField(blank=True, max_length=32)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.council",
                    ),
                ),
            ],
            options={
                "db_table": "department",
                "ordering": ["department_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("council", "department_name"),
                        name="uniq_department_name_per_council",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "department" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "department" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "department_tenant_isolation" ON "department"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "department_tenant_isolation" ON "department";',
                'ALTER TABLE "department" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "department" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
