# Generated by Django 6.1 on 2026-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="legal_basis",
            field=models.CharField(
                blank=True,
                help_text="The bye-law provision constituting this department, e.g. 'Part II, Section 6' — from the council's departmental schedule.",
                max_length=120,
            ),
        ),
    ]
