# Generated by Django 6.1 on 2026-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0004_seed_real_kac_wards"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="wardzone",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
