# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_ref', models.CharField(blank=True, max_length=32, unique=True)),
                ('payer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business'), ('GOVERNMENT', 'Government'), ('NGO', 'NGO')], max_length=16)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('nin_bvn_hash', models.CharField(blank=True, max_length=128)),
                ('tin', models.CharField(blank=True, max_length=32)),
                ('business_size', models.CharField(blank=True, choices=[('MICRO', 'Micro'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=16, null=True)),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=16)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('enumerated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enumerated_payers', to=settings.AUTH_USER_MODEL)),
                ('is_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='registry.payer')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payers', to='tenancy.wardzone')),
            ],
            options={
                'db_table': 'payer',
            },
        ),
        migrations.CreateModel(
            name='EnumeratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('PREMISES', 'Premises'), ('SHOP', 'Shop'), ('KIOSK', 'Kiosk'), ('SIGNAGE', 'Signage')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='tenancy.wardzone')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='registry.payer')),
            ],
            options={
                'db_table': 'enumerated_asset',
            },
        ),
        migrations.AddIndex(
            model_name='payer',
            index=models.Index(fields=['council', 'full_name'], name='payer_council_c13bae_idx'),
        ),
        migrations.AddIndex(
            model_name='payer',
            index=models.Index(fields=['council', 'phone'], name='payer_council_d5a49a_idx'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "payer" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "payer" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "payer_tenant_isolation" ON "payer"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "payer_tenant_isolation" ON "payer";',
                'ALTER TABLE "payer" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "payer" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "enumerated_asset" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "enumerated_asset" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "enumerated_asset_tenant_isolation" ON "enumerated_asset"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "enumerated_asset_tenant_isolation" ON "enumerated_asset";',
                'ALTER TABLE "enumerated_asset" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "enumerated_asset" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
