# Generated by Django 6.1 on 2026-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='payer_ref',
            field=models.CharField(blank=True, max_length=48, unique=True),
        ),
    ]
