# Generated by Django 6.1 on 2026-08-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_payer_payer_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
