# Generated by Django 6.1 on 2026-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0003_payer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="payer",
            name="credit_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
