# Generated by Django 6.1 on 2026-09-11 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.common.db import enable_tenant_rls_sql


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0008_remove_payer_full_name"),
        ("tenancy", "0003_department_legal_basis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PayerDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "council",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.council",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="registry.payer",
                    ),
                ),
                (
                    "proxy_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payer_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payer_delegation",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("payer", "proxy_user"),
                        name="uniq_active_delegation_per_proxy",
                    )
                ],
            },
        ),
        migrations.RunSQL(
            sql=enable_tenant_rls_sql("payer_delegation"),
            reverse_sql=[
                'DROP POLICY IF EXISTS "payer_delegation_tenant_isolation" ON "payer_delegation";',
                'ALTER TABLE "payer_delegation" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "payer_delegation" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
