# Generated by Django 6.1 on 2026-09-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0009_payer_user_payerdelegation"),
    ]

    operations = [
        migrations.AddField(
            model_name="payer",
            name="line_of_business",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
