# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('POS', 'POS'), ('OTC', 'Over-the-counter teller'), ('IB_MB', 'Internet / Mobile Banking'), ('USSD', 'USSD'), ('FIRSTMONIE', 'FirstMonie Agent Banking')], max_length=16, unique=True)),
                ('provider', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'payment_channel',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_ref', models.CharField(blank=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_txn_ref', models.CharField(blank=True, max_length=64)),
                ('txn_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='CONFIRMED', max_length=16)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.bill')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_posted', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentchannel')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='ChannelTransactionFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_txn_ref', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('EXCEPTION', 'Exception')], default='UNMATCHED', max_length=16)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_matches', to='payments.payment')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_rows', to='payments.paymentchannel')),
            ],
            options={
                'db_table': 'channel_transaction_feed',
            },
        ),
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('secret_encrypted', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_clients', to='payments.paymentchannel')),
            ],
            options={
                'db_table': 'api_client',
            },
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal_id', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FAULTY', 'Faulty'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='accounts.fieldagent')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='tenancy.wardzone')),
            ],
            options={
                'db_table': 'pos_terminal',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_ref', models.CharField(blank=True, max_length=64, unique=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['council', 'bill'], name='payment_council_a20824_idx'),
        ),
        migrations.AddConstraint(
            model_name='channeltransactionfeed',
            constraint=models.UniqueConstraint(fields=('channel', 'bank_txn_ref'), name='uniq_channel_bank_txn_ref'),
        ),
        migrations.AddConstraint(
            model_name='posterminal',
            constraint=models.UniqueConstraint(fields=('council', 'terminal_id'), name='uniq_terminal_id_per_council'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "pos_terminal" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "pos_terminal" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "pos_terminal_tenant_isolation" ON "pos_terminal"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "pos_terminal_tenant_isolation" ON "pos_terminal";',
                'ALTER TABLE "pos_terminal" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "pos_terminal" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "api_client" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "api_client" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "api_client_tenant_isolation" ON "api_client"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "api_client_tenant_isolation" ON "api_client";',
                'ALTER TABLE "api_client" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "api_client" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "payment" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "payment" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "payment_tenant_isolation" ON "payment"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "payment_tenant_isolation" ON "payment";',
                'ALTER TABLE "payment" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "payment" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "channel_transaction_feed" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "channel_transaction_feed" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "channel_transaction_feed_tenant_isolation" ON "channel_transaction_feed"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "channel_transaction_feed_tenant_isolation" ON "channel_transaction_feed";',
                'ALTER TABLE "channel_transaction_feed" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "channel_transaction_feed" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "receipt" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "receipt" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "receipt_tenant_isolation" ON "receipt"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "receipt_tenant_isolation" ON "receipt";',
                'ALTER TABLE "receipt" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "receipt" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
