# Generated by Django 6.1 on 2026-08-18 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.posterminal",
            ),
        ),
        migrations.AddField(
            model_name="posterminal",
            name="bank_terminal_id",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
