# Generated by Django 6.1 on 2026-09-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_terminal_posterminal_bank_terminal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentchannel",
            name="code",
            field=models.CharField(
                choices=[
                    ("POS", "POS"),
                    ("OTC", "Over-the-counter teller"),
                    ("IB_MB", "Internet / Mobile Banking"),
                    ("USSD", "USSD"),
                    ("FIRSTMONIE", "FirstMonie Agent Banking"),
                    ("CASH", "Cash"),
                ],
                max_length=16,
                unique=True,
            ),
        ),
    ]
