# Generated by Django 6.1 on 2026-09-10 12:17

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_add_cash_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiclient",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Null means the key never expires.", null=True
            ),
        ),
        migrations.AddField(
            model_name="apiclient",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apiclient",
            name="scopes",
            field=models.JSONField(
                blank=True,
                default=apps.payments.models._default_api_client_scopes,
                help_text="Action codes this key may invoke — see SCOPE_CHOICES.",
            ),
        ),
    ]
