# Generated by Django 6.1 on 2026-09-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_fifo_allocation_and_itemized_arrears"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiclient",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
