# Generated by Django 6.1 on 2026-09-23 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_backfill_billline_position_and_current_amount'),
        ('payments', '0006_apiclient_name'),
        ('tenancy', '0005_department_is_active_wardzone_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_txn_ref', ''), _negated=True), fields=('channel', 'bank_txn_ref'), name='uniq_channel_bank_txn_ref_nonblank'),
        ),
    ]
