# Generated by Django 6.1 on 2026-09-23 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bill_bill_council_3a788e_idx'),
        ('payments', '0007_payment_uniq_channel_bank_txn_ref_nonblank'),
        ('tenancy', '0005_department_is_active_wardzone_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channeltransactionfeed',
            index=models.Index(fields=['council', 'received_at'], name='channel_tra_council_1f9ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='channeltransactionfeed',
            index=models.Index(fields=['council', 'match_status'], name='channel_tra_council_b00699_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['council', 'created_at'], name='payment_council_f32d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['council', 'txn_status'], name='payment_council_a0b077_idx'),
        ),
    ]
