# Generated by Django 6.1 on 2026-09-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0008_channeltransactionfeed_channel_tra_council_1f9ff6_idx_and_more",
        ),
        ("tenancy", "0005_department_is_active_wardzone_is_active"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["council", "-created_at"], name="receipt_council_created_idx"
            ),
        ),
    ]
