# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'revenue categories',
                'db_table': 'revenue_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CouncilRevenueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harmonised_code', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=160)),
                ('unit_of_charge', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='council_items', to='revenue.revenuecategory')),
            ],
            options={
                'db_table': 'council_revenue_item',
                'ordering': ['harmonised_code'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='accounts.subconsultant')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_entries', to='tenancy.wardzone')),
                ('council_revenue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_entries', to='revenue.councilrevenueitem')),
            ],
            options={
                'db_table': 'consultant_portfolio',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='RevenueItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('harmonised_code', models.CharField(max_length=32, unique=True)),
                ('item_name', models.CharField(max_length=160)),
                ('unit_of_charge', models.CharField(max_length=64)),
                ('in_initial_scope', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_templates', to='revenue.revenuecategory')),
            ],
            options={
                'db_table': 'revenue_item_template',
                'ordering': ['harmonised_code'],
            },
        ),
        migrations.AddField(
            model_name='councilrevenueitem',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='council_activations', to='revenue.revenueitemtemplate'),
        ),
        migrations.CreateModel(
            name='RateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('council_revenue_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_schedules', to='revenue.councilrevenueitem')),
            ],
            options={
                'db_table': 'rate_schedule',
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('council_revenue_item',), name='uniq_open_rate_per_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='councilrevenueitem',
            constraint=models.UniqueConstraint(fields=('council', 'harmonised_code'), name='uniq_item_code_per_council'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "council_revenue_item" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "council_revenue_item" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "council_revenue_item_tenant_isolation" ON "council_revenue_item"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "council_revenue_item_tenant_isolation" ON "council_revenue_item";',
                'ALTER TABLE "council_revenue_item" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "council_revenue_item" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "consultant_portfolio" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "consultant_portfolio" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "consultant_portfolio_tenant_isolation" ON "consultant_portfolio"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "consultant_portfolio_tenant_isolation" ON "consultant_portfolio";',
                'ALTER TABLE "consultant_portfolio" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "consultant_portfolio" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
