# Generated by Django 6.1 on 2026-08-18 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text="The gazette's sub-classification name, e.g. 'Beer parlor'. Blank only when the item has exactly one band standing in for the whole item (no sub-classification), e.g. Communication Mast's single Large/Medium/Small triple.", max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('rate_mode', models.CharField(choices=[('FLAT', 'Flat'), ('RANGE', 'Range'), ('TIERED', 'Tiered')], max_length=16)),
                ('flat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('council_revenue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_bands', to='revenue.councilrevenueitem')),
            ],
            options={
                'db_table': 'rate_band',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='revenue.rateband')),
            ],
            options={
                'db_table': 'rate_tier',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='rateband',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('council_revenue_item', 'label'), name='uniq_open_band_label_per_item'),
        ),
        migrations.AddConstraint(
            model_name='rateband',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('flat_amount__isnull', False), ('max_amount__isnull', True), ('min_amount__isnull', True), ('rate_mode', 'FLAT')), models.Q(('flat_amount__isnull', True), ('max_amount__isnull', False), ('min_amount__isnull', False), ('rate_mode', 'RANGE')), models.Q(('flat_amount__isnull', True), ('max_amount__isnull', True), ('min_amount__isnull', True), ('rate_mode', 'TIERED')), _connector='OR'), name='rate_band_amount_fields_match_mode'),
        ),
        migrations.AddConstraint(
            model_name='ratetier',
            constraint=models.UniqueConstraint(fields=('band', 'label'), name='uniq_tier_label_per_band'),
        ),
    ]
