# Generated by Django 6.1 on 2026-08-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('revenue', '0003_agentportfolio'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentportfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('agent', 'council_revenue_item', 'ward'), name='uniq_open_agent_portfolio_item_ward', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='consultantportfolio',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('consultant', 'council_revenue_item', 'ward'), name='uniq_open_consultant_portfolio_item_ward', nulls_distinct=False),
        ),
    ]
