# Generated by Django 6.1 on 2026-09-01 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0004_agentportfolio_uniq_open_agent_portfolio_item_ward_and_more"),
        ("tenancy", "0002_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="councilrevenueitem",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revenue_items",
                to="tenancy.department",
            ),
        ),
    ]
