# Generated by Django 6.1 on 2026-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0005_councilrevenueitem_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="councilrevenueitem",
            name="bye_law_description",
            field=models.TextField(
                blank=True,
                help_text="What that bye-law provision actually authorises, in the council's own wording — carried over verbatim rather than paraphrased.",
            ),
        ),
        migrations.AddField(
            model_name="councilrevenueitem",
            name="bye_law_reference",
            field=models.CharField(
                blank=True,
                help_text="The Part/Section of the council's bye-laws this item is charged under, e.g. 'Part XXI' — the citation a demand notice or objection has to quote.",
                max_length=64,
            ),
        ),
    ]
