# Generated by Django 6.1 on 2026-09-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0006_councilrevenueitem_bye_law_description_and_more"),
        ("tenancy", "0004_seed_real_kac_wards"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="councilrevenueitem",
            name="uniq_item_code_per_council",
        ),
        migrations.AddConstraint(
            model_name="councilrevenueitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("council", "harmonised_code"),
                name="uniq_item_code_per_council",
            ),
        ),
    ]
