# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_collections', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('COMPUTED', 'Computed'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled'), ('DISPUTED', 'Disputed')], default='COMPUTED', max_length=16)),
                ('computed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_computed', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='accounts.subconsultant')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
            ],
            options={
                'db_table': 'commission_settlement',
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('consultant', 'period_start', 'period_end'), name='uniq_settlement_per_period')],
            },
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "commission_settlement" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "commission_settlement" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "commission_settlement_tenant_isolation" ON "commission_settlement"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "commission_settlement_tenant_isolation" ON "commission_settlement";',
                'ALTER TABLE "commission_settlement" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "commission_settlement" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
