# Generated by Django 6.1 on 2026-09-23 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_appuser_must_change_password'),
        ('settlements', '0001_initial'),
        ('tenancy', '0005_department_is_active_wardzone_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commissionsettlement',
            index=models.Index(fields=['council', 'status'], name='commission__council_fe746b_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionsettlement',
            index=models.Index(fields=['council', 'period_start'], name='commission__council_b0478a_idx'),
        ),
    ]
