# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_date', models.DateField()),
                ('total_platform', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_bank', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BALANCED', 'Balanced'), ('EXCEPTIONS', 'Exceptions'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='payments.paymentchannel')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reconciliation_run',
                'ordering': ['-run_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
                ('feed_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='payments.channeltransactionfeed')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_exceptions', to='payments.payment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exceptions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='reconciliation.reconciliationrun')),
            ],
            options={
                'db_table': 'reconciliation_exception',
            },
        ),
        migrations.AddConstraint(
            model_name='reconciliationrun',
            constraint=models.UniqueConstraint(fields=('council', 'channel', 'run_date'), name='uniq_recon_run_per_day'),
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "reconciliation_run" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "reconciliation_run" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "reconciliation_run_tenant_isolation" ON "reconciliation_run"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "reconciliation_run_tenant_isolation" ON "reconciliation_run";',
                'ALTER TABLE "reconciliation_run" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "reconciliation_run" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "reconciliation_exception" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "reconciliation_exception" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "reconciliation_exception_tenant_isolation" ON "reconciliation_exception"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "reconciliation_exception_tenant_isolation" ON "reconciliation_exception";',
                'ALTER TABLE "reconciliation_exception" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "reconciliation_exception" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
