# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['council', 'entity_type', 'entity_id'], name='audit_log_council_dbc4ea_idx')],
            },
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "audit_log" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "audit_log" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "audit_log_tenant_isolation" ON "audit_log"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "audit_log_tenant_isolation" ON "audit_log";',
                'ALTER TABLE "audit_log" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "audit_log" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
