# Generated by Django 6.1 on 2026-09-23 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tenancy', '0005_department_is_active_wardzone_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['council', 'created_at'], name='audit_log_council_16cb08_idx'),
        ),
    ]
