# Generated by Django 6.1 on 2026-08-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ageing_bucket', models.CharField(choices=[('0_30', '0-30 days'), ('31_60', '31-60 days'), ('61_90', '61-90 days'), ('OVER_90', '90+ days')], default='0_30', max_length=8)),
                ('enforcement_stage', models.CharField(choices=[('NONE', 'None'), ('FIRST_NOTICE', 'First Notice'), ('FINAL_NOTICE', 'Final Notice'), ('ENFORCEMENT', 'Enforcement'), ('LEGAL', 'Legal'), ('CLOSED', 'Closed')], default='FIRST_NOTICE', max_length=16)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt_case', to='billing.bill')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.council')),
            ],
            options={
                'db_table': 'debt_case',
            },
        ),
        migrations.RunSQL(
            sql=[
                'ALTER TABLE "debt_case" ENABLE ROW LEVEL SECURITY;',
                'ALTER TABLE "debt_case" FORCE ROW LEVEL SECURITY;',
                """
                CREATE POLICY "debt_case_tenant_isolation" ON "debt_case"
                USING (council_id = NULLIF(current_setting('app.council_id', true), '')::integer)
                WITH CHECK (council_id = NULLIF(current_setting('app.council_id', true), '')::integer);
                """,
            ],
            reverse_sql=[
                'DROP POLICY IF EXISTS "debt_case_tenant_isolation" ON "debt_case";',
                'ALTER TABLE "debt_case" NO FORCE ROW LEVEL SECURITY;',
                'ALTER TABLE "debt_case" DISABLE ROW LEVEL SECURITY;',
            ],
        ),
    ]
